In [1]:
import pandas as pd
Edges = pd.read_csv('NA_Checked_Lemma_NPMI2_10.csv', sep='\t')
Edges

,word1,attr1,word2,attr2,word1 freq,word2 freq,bigram freq,score trimmed,distance,similarity,period,genre,combined,url
0,Aššur[1]DN,[?],iššiakku[city-ruler]N,[?],2246,193,364,0.553,1.242,0.684,NaN,NaN,NaN,https://korp.csc.fi/test-as/?mode=other_langua...
1,Aššur[1]DN,[?],Ištar[1]DN,[?],2246,1040,504,0.329,4.127,0.707,NaN,NaN,NaN,https://korp.csc.fi/test-as/?mode=other_langua...
2,Aššur[1]DN,[?],Enlil[1]DN,[?],2246,456,278,0.274,2.579,0.649,NaN,NaN,NaN,https://korp.csc.fi/test-as/?mode=other_langua...
3,Aššur[1]DN,[?],Mullissu[1]DN,[?],2246,297,207,0.253,2.391,0.490,NaN,NaN,NaN,https://korp.csc.fi/test-as/?mode=other_langua...
4,Aššur[1]DN,[?],ilu[god]N,[?],2246,3545,668,0.235,3.749,0.601,NaN,NaN,NaN,https://korp.csc.fi/test-as/?mode=other_langua...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3989,ṭēmu[(fore)thought]N,[?],muhhu[skull]N,[?],690,3507,171,0.109,4.164,0.426,NaN,NaN,NaN,https://korp.csc.fi/test-as/?mode=other_langua...
3990,ṭēmu[(fore)thought]N,[?],harṣu[broken-off]AJ,[?],690,13,10,0.106,2.300,0.106,NaN,NaN,NaN,https://korp.csc.fi/test-as/?mode=other_langua...
3991,ṭēmu[(fore)thought]N,[?],muterru[(re)turner]N,[?],690,44,15,0.086,1.000,0.137,NaN,NaN,NaN,https://korp.csc.fi/test-as/?mode=other_langua...
3992,ṭēmu[(fore)thought]N,[?],alāku[go]V,[?],690,3964,142,0.085,4.556,0.379,NaN,NaN,NaN,https://korp.csc.fi/test-as/?mode=other_langua...
3993,ṭēmānu_AJ[wise]AJ,[?],libbu[interior]N,[?],1,4805,2,0.029,8.000,0.029,NaN,NaN,NaN,https://korp.csc.fi/test-as/?mode=other_langua...

In [2]:
SourceTarget = Edges[['word1', 'word2', 'score trimmed']]
SourceTarget

                     word1                  word2  score trimmed
0               Aššur[1]DN  iššiakku[city-ruler]N          0.553
1               Aššur[1]DN             Ištar[1]DN          0.329
2               Aššur[1]DN             Enlil[1]DN          0.274
3               Aššur[1]DN          Mullissu[1]DN          0.253
4               Aššur[1]DN              ilu[god]N          0.235
...                    ...                    ...            ...
3989  ṭēmu[(fore)thought]N          muhhu[skull]N          0.109
3990  ṭēmu[(fore)thought]N    harṣu[broken-off]AJ          0.106
3991  ṭēmu[(fore)thought]N   muterru[(re)turner]N          0.086
3992  ṭēmu[(fore)thought]N             alāku[go]V          0.085
3993     ṭēmānu_AJ[wise]AJ       libbu[interior]N          0.029

[3994 rows x 3 columns]

In [3]:
SourceTarget.rename(columns={'word1':'Sources', 'word2':'Targets', 'score trimmed':'weight'}, inplace=True)
SourceTarget

C:\Hyapp\Anaconda3-2019.3\lib\site-packages\pandas\core\frame.py:4238: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(**kwargs)

                   Sources                Targets  weight
0               Aššur[1]DN  iššiakku[city-ruler]N   0.553
1               Aššur[1]DN             Ištar[1]DN   0.329
2               Aššur[1]DN             Enlil[1]DN   0.274
3               Aššur[1]DN          Mullissu[1]DN   0.253
4               Aššur[1]DN              ilu[god]N   0.235
...                    ...                    ...     ...
3989  ṭēmu[(fore)thought]N          muhhu[skull]N   0.109
3990  ṭēmu[(fore)thought]N    harṣu[broken-off]AJ   0.106
3991  ṭēmu[(fore)thought]N   muterru[(re)turner]N   0.086
3992  ṭēmu[(fore)thought]N             alāku[go]V   0.085
3993     ṭēmānu_AJ[wise]AJ       libbu[interior]N   0.029

[3994 rows x 3 columns]

In [5]:
#open nodes file
Nodes = pd.read_csv('NodeListCheckedLemmaNADN-Copy1.csv', sep=',')
Nodes

        Id                               Label
0        1                        Lamaštu[1]DN
1        2                 Ušumgallu[dragon]DN
2        3                   abru[strong-one]N
3        4                     ahurrû[junior]N
4        5  ariru[(a-priest-uttering-curses)]N
...    ...                                 ...
2202  2203                       muhhu[skull]N
2203  2204                 harṣu[broken-off]AJ
2204  2205                muterru[(re)turner]N
2205  2206                          alāku[go]V
2206  2207                    libbu[interior]N

[2207 rows x 2 columns]

In [6]:
#rename 'word1'to prepare this for the merge later on with the Edges table
Nodes.rename(columns={'Label':'Sources','Id':'Source'}, inplace=True)
Nodes

      Source                             Sources
0          1                        Lamaštu[1]DN
1          2                 Ušumgallu[dragon]DN
2          3                   abru[strong-one]N
3          4                     ahurrû[junior]N
4          5  ariru[(a-priest-uttering-curses)]N
...      ...                                 ...
2202    2203                       muhhu[skull]N
2203    2204                 harṣu[broken-off]AJ
2204    2205                muterru[(re)turner]N
2205    2206                          alāku[go]V
2206    2207                    libbu[interior]N

[2207 rows x 2 columns]

In [7]:
#Trying to merge SourceTarget and Nodes on 'Sources',
SourceTarget1 = pd.merge(SourceTarget, Nodes, on='Sources')
SourceTarget1

                   Sources                Targets  weight  Source
0               Aššur[1]DN  iššiakku[city-ruler]N   0.553    1868
1               Aššur[1]DN             Ištar[1]DN   0.329    1868
2               Aššur[1]DN             Enlil[1]DN   0.274    1868
3               Aššur[1]DN          Mullissu[1]DN   0.253    1868
4               Aššur[1]DN              ilu[god]N   0.235    1868
...                    ...                    ...     ...     ...
3989  ṭēmu[(fore)thought]N          muhhu[skull]N   0.109    1234
3990  ṭēmu[(fore)thought]N    harṣu[broken-off]AJ   0.106    1234
3991  ṭēmu[(fore)thought]N   muterru[(re)turner]N   0.086    1234
3992  ṭēmu[(fore)thought]N             alāku[go]V   0.085    1234
3993     ṭēmānu_AJ[wise]AJ       libbu[interior]N   0.029     170

[3994 rows x 4 columns]

In [8]:
SourceTarget2 = SourceTarget1 [['Source', 'Targets', 'weight']]
SourceTarget2

      Source                Targets  weight
0       1868  iššiakku[city-ruler]N   0.553
1       1868             Ištar[1]DN   0.329
2       1868             Enlil[1]DN   0.274
3       1868          Mullissu[1]DN   0.253
4       1868              ilu[god]N   0.235
...      ...                    ...     ...
3989    1234          muhhu[skull]N   0.109
3990    1234    harṣu[broken-off]AJ   0.106
3991    1234   muterru[(re)turner]N   0.086
3992    1234             alāku[go]V   0.085
3993     170       libbu[interior]N   0.029

[3994 rows x 3 columns]

In [9]:
Nodes1 = Nodes
Nodes1

      Source                             Sources
0          1                        Lamaštu[1]DN
1          2                 Ušumgallu[dragon]DN
2          3                   abru[strong-one]N
3          4                     ahurrû[junior]N
4          5  ariru[(a-priest-uttering-curses)]N
...      ...                                 ...
2202    2203                       muhhu[skull]N
2203    2204                 harṣu[broken-off]AJ
2204    2205                muterru[(re)turner]N
2205    2206                          alāku[go]V
2206    2207                    libbu[interior]N

[2207 rows x 2 columns]

In [10]:
Nodes1.rename(columns={'Sources':'Targets','Source':'Target'}, inplace=True)
Nodes1

      Target                             Targets
0          1                        Lamaštu[1]DN
1          2                 Ušumgallu[dragon]DN
2          3                   abru[strong-one]N
3          4                     ahurrû[junior]N
4          5  ariru[(a-priest-uttering-curses)]N
...      ...                                 ...
2202    2203                       muhhu[skull]N
2203    2204                 harṣu[broken-off]AJ
2204    2205                muterru[(re)turner]N
2205    2206                          alāku[go]V
2206    2207                    libbu[interior]N

[2207 rows x 2 columns]

In [11]:
SourceTarget3 = pd.merge(SourceTarget2, Nodes1, on='Targets')
SourceTarget3

      Source                  Targets  weight  Target
0       1868    iššiakku[city-ruler]N   0.553     837
1       2135    iššiakku[city-ruler]N   0.255     837
2       1868               Ištar[1]DN   0.329    1367
3       1367               Ištar[1]DN   0.382    1367
4        581               Ištar[1]DN   0.185    1367
...      ...                      ...     ...     ...
3989     915  nesû[be(come)-distant]V   0.135    2187
3990    1234       harāṣu[break-off]V   0.138    2201
3991    1234        ṭêmu[look-after]V   0.114    2202
3992    1234      harṣu[broken-off]AJ   0.106    2204
3993    1234     muterru[(re)turner]N   0.086    2205

[3994 rows x 4 columns]

In [12]:
SourceTarget4 = SourceTarget3 [['Source', 'Target', 'weight']]
SourceTarget4

      Source  Target  weight
0       1868     837   0.553
1       2135     837   0.255
2       1868    1367   0.329
3       1367    1367   0.382
4        581    1367   0.185
...      ...     ...     ...
3989     915    2187   0.135
3990    1234    2201   0.138
3991    1234    2202   0.114
3992    1234    2204   0.106
3993    1234    2205   0.086

[3994 rows x 3 columns]

In [12]:
#keep: KORP, score_trimmed, bigram frequency
#find word 1 in Label column in Nodes file, return Id in same row
#above for word 2
#change headings to: source, target

In [13]:
#save as a .csv file
savefile =  'EdgeListCheckedLemmaNADN.csv'
with open('output/' + savefile, 'w', encoding="utf-8") as w:
    SourceTarget4.to_csv(w, index=False)